# PyMOL script to load aligned Class B GPCR structures
# Generated by Session 3

load 8jr9.cif, 8jr9
load 6nbf.cif, 6nbf
load 7lci.cif, 7lci
load 6x18.cif, 6x18

# Color by structure
color cyan, 8jr9
color magenta, 6nbf
color yellow, 7lci
color green, 6x18

# Show binding pocket region
select binding_pocket, resi 219+223+299+302+413+415+417+458+459
show sticks, binding_pocket
zoom binding_pocket
