# PyMOL visualization script for PCO371 binding site
# Generated by Session 3

# Load the structure
fetch 8jr9, async=0

# Hide everything first
hide all

# Show cartoon for receptor
show cartoon, chain R
color lightblue, chain R

# Find and show the ligand
select ligand, hetatm and not resn HOH
show sticks, ligand
color yellow, ligand

# Show binding site residues
select binding_site, chain R and resi 414+459+391+463+458+223+413+417+302+415+416+299+412+219+411
show sticks, binding_site
color salmon, binding_site

# Label key residues
label binding_site and name CA, "%s%s" % (resn, resi)
set label_size, 14

# Zoom to binding site
zoom binding_site, 5

# Add measurements to key residues
# distance dist_p415, ligand, resi 415 and name CA

# Save session
# save pco371_binding_site.pse

# Print summary
print "Binding site visualization loaded."
print "Yellow = ligand, Salmon = binding residues, Blue = receptor"
