#!/bin/bash
# Boltz-2 submission script for PTH1R saturation mutagenesis
# Generated by Session 3
# Target: Position 6.47b (P415) - 5 variants

boltz predict PTH1R_P415A.yaml --output boltz_out_PTH1R_P415A
boltz predict PTH1R_P415C.yaml --output boltz_out_PTH1R_P415C
boltz predict PTH1R_P415D.yaml --output boltz_out_PTH1R_P415D
boltz predict PTH1R_P415E.yaml --output boltz_out_PTH1R_P415E
boltz predict PTH1R_P415F.yaml --output boltz_out_PTH1R_P415F
